
export const SAITA_DETAILS_REQUESTED = "SAITA_DETAILS_REQUESTED";
export const SAITA_DETAILS_SUCCESS = 'SAITA_DETAILS_SUCCESS';
export const SAITA_DETAILS_REQUEST_FAILED = 'SAITA_DETAILS_REQUEST_FAILED';